/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/earth.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    earth_1: THREE.Mesh
    earth_2: THREE.Mesh
  }
  materials: {
    clouds_MAT: THREE.MeshStandardMaterial
    earth_MAT: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/earth.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.earth_1.geometry} material={materials.clouds_MAT} />
        <mesh geometry={nodes.earth_2.geometry} material={materials.earth_MAT} />
      </group>
    </group>
  )
}

useGLTF.preload('/earth.glb')
