import type { Metadata } from "next";
import { Noto_Serif_JP,  Inter } from "next/font/google";
import "./globals.scss";
import ScrollContainer from "@/components/scrollContainer";
import Header from "@/components/header";
import Footer from "@/components/footer";

const noto = Noto_Serif_JP({ 
  weight: ['300','400','500','700','900'],
  subsets: ["latin"]
 });

 const inter = Inter({ 
  weight: ['300','400','500','700'],
  subsets: ["latin"],
  variable: '--font-inter'
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto.className} ${inter.variable} bg-[url(/assets/images/bg-main.jpg)] text-white`}>
        <ScrollContainer>
          <div className="bg-[url(/assets/images/text-footer.svg)] md:bg-right-bottom bg-[bottom_200px_right] bg-no-repeat max-lg:bg-[size:70%_auto] max-md:bg-[size:300px_auto]">
            <Header />
            {children}
            <Footer />
          </div>
        </ScrollContainer>
        </body>
    </html>
  );
}
