import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollContainer from "@/components/scrollContainer";

const noto = Noto_Sans_JP({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body
        className={`${noto.className}`}
      >
        <ScrollContainer>
          <div className="">
            <Header />
            {children}
            <Footer />
          </div>
        </ScrollContainer>
      </body>
    </html>
  );
}
