'use client'

export default function Program() {
  return (
    <section className="relative z-10 md:pt-20 pt-12 md:pb-[100px] pb-16">
        <div className="absolute inset-0 w-full h-full overflow-hidden">
            <div className="absolute inset-0 bg-black/70 z-10"></div>
            <video
          className="w-full h-full object-cover relative opacity-60"
          data-lazy-video=""
          data-lazy=""
          data-autoplay="true"
          preload="none"
          loop
          muted
          autoPlay
          src="/assets/videos/program.mp4"
          playsInline
          data-loaded="true"
        ></video>
        </div>
       <div className="w-full max-w-[1440px] mx-auto md:pl-10 lg:pl-[120px] md:pr-10 px-5 relative z-20">
          <div className="flex relative max-md:flex-col md:items-end md:gap-[50px] gap-5">
            <div className="w-full md:max-w-[550px] relative md:pb-[340px]">
                <p className="fade-up md:text-[40px] text-[24px] font-bold italic border-b border-white tracking-wider pb-2">Buyback and Burn Program</p>
                <p className="fade-up md:text-[18px] text-[14px] lg:pt-6 md:pt-5 pt-3 leading-loose tracking-wider">
                    A portion of the transaction fees generated by Teleport Exchange will be used to buy back TEXC from the market, <br />
                    <br />
                    which will be permanently burned, gradually reducing the total supply.
                </p>
            </div>
            <div className="w-full lg:px-[60px] md:px-5 md:py-10 py-8 relative">
                <p className="fade-up md:text-[32px] text-[22px] font-bold tracking-wider text-[#FFFF01] leading-loose">veToken System</p>
                <p className="fade-up md:text-[20px] text-[16px] lg:pt-6 md:pt-5 pt-3 leading-loose tracking-wider">
                   By locking your TEXC for a period of time, you can receive additional benefits:
                </p>
                <ul className="fade-up md:pt-6 pt-4">
                    {[
                        "Increase in voting power according to lock period",
                        "Partial distribution of protocol revenue",
                        "Priority for exclusive NFTs and airdrops",
                    ].map((item, index) => (
                        <li key={index} className="md:text-[18px] text-[14px] leading-loose flex gap-1">
                            <span className="mt-1.5 md:mt-2.5"><img src="/assets/images/ic-reward.svg " alt="" /></span>
                            {item}
                        </li>
                    ))}
                </ul>
            </div>
          </div>
       </div>
    </section>
  )
}