import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollContainer from "@/components/scrollContainer";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';


const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

export default async function LocaleLayout({
  children,params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html  lang={locale}>
       <body
        className={`${inter.className} bg-black`}
      >
        <NextIntlClientProvider>
        <ScrollContainer>
          <div className="">
            <Header />
            {children}
            <Footer />
          </div>
        </ScrollContainer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
